# Generated by Django 6.0.1 on 2026-02-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document_processing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="file_key",
            field=models.CharField(default="", max_length=500),
        ),
        migrations.AddField(
            model_name="document",
            name="file_size",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="original_filename",
            field=models.CharField(default="", max_length=250),
        ),
    ]
