# Generated by Django 6.0.1 on 2026-08-05 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document_processing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="extracted_data",
            field=models.TextField(blank=True, null=True),
        ),
    ]
