# Generated by Django 6.0.1 on 2026-02-26 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document_processing", "0002_document_file_key_document_file_size_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="extracted_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
